version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "8080:5678"  # Direct HTTP access on port 8080
    environment:
      - N8N_HOST=195.35.56.159
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://195.35.56.159:8080/
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - /local-files:/files

volumes:
  n8n_data:
    external: true