version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: whisnap-postgres
    environment:
      POSTGRES_DB: whisnap_db
      POSTGRES_USER: whisnap_user
      POSTGRES_PASSWORD: whisnap_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: