services:
  web:
    container_name: web-blue
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-whisnap_user}:${DATABASE_PASSWORD}@postgres-shared:5432/${DATABASE_NAME:-whisnap_db}
    networks:
      - whisnap-network
      - edge

  api:
    container_name: api-blue
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-whisnap_user}:${DATABASE_PASSWORD}@postgres-shared:5432/${DATABASE_NAME:-whisnap_db}
    networks:
      - whisnap-network
      - edge


networks:
  edge:
    external: true