services:
  web:
    container_name: web-blue
    networks:
      - whisnap-network
      - edge

  api:
    container_name: api-blue
    networks:
      - whisnap-network
      - edge


networks:
  edge:
    external: true