services:
  web:
    container_name: web-blue
    networks:
      - whisnap-network
      - edge

  api:
    container_name: api-blue
    networks:
      - whisnap-network
      - edge

  # Exclude nginx from blue-green deployment
  nginx:
    deploy:
      replicas: 0

networks:
  edge:
    external: true