# =============================================================================
# Consolidated Docker Compose: Blue-Green Compatible with Network Aliases
# =============================================================================

services:
  # Next.js Web Application
  web:
    image: ghcr.io/neolio42/whisnap-web:${IMAGE_TAG}
    env_file:
      - ../.env.prod
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      whisnap-network:
      edge:
        aliases:
          - ${COLOR:-blue}-web
          - app-web-${COLOR:-blue}
    volumes:
      - web_uploads:/app/uploads
    # Modern health check with 2025 features
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    # Security hardening
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
    # Log rotation
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Express API
  api:
    image: ghcr.io/neolio42/whisnap-api:${IMAGE_TAG}
    env_file:
      - ../.env.prod
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://web:3000
      - API_PORT=4000
      - WS_PORT=4001
    expose:
      - "4000"
      - "4001"
    restart: unless-stopped
    networks:
      whisnap-network:
      edge:
        aliases:
          - ${COLOR:-blue}-api
          - app-api-${COLOR:-blue}
    volumes:
      - api_logs:/app/logs
      - api_uploads:/app/uploads
    # Modern health check with 2025 features
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/v1/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    # Security hardening
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    # Log rotation
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Cache (Optional - for session caching and rate limiting)
  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-whisnap_redis}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - whisnap-network
    profiles:
      - cache
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data_prod:
    driver: local
  web_uploads:
    driver: local
  api_logs:
    driver: local
  api_uploads:
    driver: local
  nginx_logs:
    driver: local
  redis_data:
    driver: local

networks:
  whisnap-network:
    driver: bridge
  edge:
    external: true