# Shared PostgreSQL Database for Blue-Green Deployment
# This runs as a singleton service shared by both blue and green stacks

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-whisnap_db}
      POSTGRES_USER: ${DATABASE_USER:-whisnap_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    expose:
      - "5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - whisnap-network
      - edge
    command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-whisnap_user} -d ${DATABASE_NAME:-whisnap_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
    driver: local

networks:
  whisnap-network:
    external: true
  edge:
    external: true